module.exports = (instance) => [
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get API Version',
      style: { text: 'Get API Ver', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getApiVersion', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get Signal In Status',
      style: { text: 'Get Signal In', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemSignalIn', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get Signal Out Status',
      style: { text: 'Get Signal Out', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemSignalOut', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get LAN Status',
      style: { text: 'Get LAN', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemLan', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get WiFi Status',
      style: { text: 'Get WiFi', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemWifi', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get System Temperature',
      style: { text: 'Get Temp', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemTemperature', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get System Fan Status',
      style: { text: 'Get Fan', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemFan', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get System Version',
      style: { text: 'Get Version', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemVersion', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get Device SWID',
      style: { text: 'Get SWID', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemDeviceSwid', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get Device HWID',
      style: { text: 'Get HWID', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemDeviceHwid', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get Device Vendor Name',
      style: { text: 'Get Vendor', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemDeviceVendorName', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get Device Model Name',
      style: { text: 'Get Model', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemDeviceModelName', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get Device Serial',
      style: { text: 'Get Serial', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemDeviceSerial', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get Device Firmware',
      style: { text: 'Get Firmware', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemDeviceFirmware', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get Device Firmware Date',
      style: { text: 'Get FW Date', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemDeviceFirmwareDate', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get Device MAC Address',
      style: { text: 'Get MAC', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemDeviceMac', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'System Registers',
      name: 'Get Device WiFi MAC Address',
      style: { text: 'Get WiFi MAC', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSystemDeviceWifiMac', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Device Name',
      style: { text: 'Get Dev Name', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemDeviceName', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Device Name',
      style: { text: 'Set Dev Name', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemDeviceName', options: { value: '' } }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Venue Name',
      style: { text: 'Get Venue', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemVenueName', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Venue Name',
      style: { text: 'Set Venue', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemVenueName', options: { value: '' } }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Customer Name',
      style: { text: 'Get Cust Name', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemCustomerName', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Customer Name',
      style: { text: 'Set Cust Name', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemCustomerName', options: { value: '' } }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Asset Tag',
      style: { text: 'Get Asset Tag', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemAssetTag', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Asset Tag',
      style: { text: 'Set Asset Tag', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemAssetTag', options: { value: '' } }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Installer Name',
      style: { text: 'Get Installer', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemInstallerName', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Installer Name',
      style: { text: 'Set Installer', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemInstallerName', options: { value: '' } }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Contact Info',
      style: { text: 'Get Contact', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemContactInfo', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Contact Info',
      style: { text: 'Set Contact', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemContactInfo', options: { value: '' } }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Install Date',
      style: { text: 'Get Inst Date', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemInstallDate', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Install Date',
      style: { text: 'Set Inst Date', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemInstallDate', options: { value: '' } }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Install Notes',
      style: { text: 'Get Inst Notes', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemInstallNotes', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Install Notes',
      style: { text: 'Set Inst Notes', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemInstallNotes', options: { value: '' } }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Locating',
      style: { text: 'Get Locating', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemLocating', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Locating',
      style: { text: 'Set Locating', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemLocating', options: { value: '0' } }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Custom 1',
      style: { text: 'Get Custom 1', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemCustom1', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Custom 1',
      style: { text: 'Set Custom 1', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemCustom1', options: { value: '' } }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Custom 2',
      style: { text: 'Get Custom 2', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemCustom2', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Custom 2',
      style: { text: 'Set Custom 2', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemCustom2', options: { value: '' } }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Get Custom 3',
      style: { text: 'Get Custom 3', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'getSetupSystemCustom3', options: {} }], up: [] }],
      feedbacks: [],
    },
    {
      type: 'button',
      category: 'Setup System Registers',
      name: 'Set Custom 3',
      style: { text: 'Set Custom 3', size: '14', color: '16777215' },
      steps: [{ down: [{ actionId: 'setSetupSystemCustom3', options: { value: '' } }], up: [] }],
      feedbacks: [],
    },
  ];